import type { Metadata } from 'next';
import { Meow_Script, Merriweather, Raleway } from 'next/font/google';
import './lib/assets/css/01_reset.css';
import './lib/assets/css/02_variables.css';
import './lib/assets/css/03_globals.css';

const heroFont = Meow_Script({
    variable: '--font-hero',
    weight: '400',
});

const headingsFont = Merriweather({
    variable: '--font-headings',
    weight: '700',
});

const bodyFont = Raleway({
    variable: '--font-body',
    weight: ['400', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${heroFont.variable} ${headingsFont.variable} ${bodyFont.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
