import '@/assets/scss/01_reset.scss';
import '@/assets/scss/02_globals.scss';
import type { Metadata } from 'next';
import { Meow_Script, Merriweather, Raleway } from 'next/font/google';

const heroFont = Meow_Script({
  variable: '--font-hero',
  weight: '400',
});

const headingsFont = Merriweather({
  variable: '--font-headings',
  weight: '700',
});

const bodyFont = Raleway({
  variable: '--font-body',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${heroFont.variable} ${headingsFont.variable} ${bodyFont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
