export type Styles = {
  'scroll-morpher__container': string;
  'scroll-morpher__container--vertical': string;
  'scroll-morpher__content': string;
  'scroll-morpher__content--gap-0': string;
  'scroll-morpher__content--gap-100': string;
  'scroll-morpher__content--gap-1000': string;
  'scroll-morpher__content--gap-1200': string;
  'scroll-morpher__content--gap-1400': string;
  'scroll-morpher__content--gap-1600': string;
  'scroll-morpher__content--gap-200': string;
  'scroll-morpher__content--gap-2000': string;
  'scroll-morpher__content--gap-2400': string;
  'scroll-morpher__content--gap-300': string;
  'scroll-morpher__content--gap-400': string;
  'scroll-morpher__content--gap-4000': string;
  'scroll-morpher__content--gap-500': string;
  'scroll-morpher__content--gap-600': string;
  'scroll-morpher__content--gap-700': string;
  'scroll-morpher__content--gap-800': string;
  'scroll-morpher__content--gap-x-0': string;
  'scroll-morpher__content--gap-x-100': string;
  'scroll-morpher__content--gap-x-1000': string;
  'scroll-morpher__content--gap-x-1200': string;
  'scroll-morpher__content--gap-x-1400': string;
  'scroll-morpher__content--gap-x-1600': string;
  'scroll-morpher__content--gap-x-200': string;
  'scroll-morpher__content--gap-x-2000': string;
  'scroll-morpher__content--gap-x-2400': string;
  'scroll-morpher__content--gap-x-300': string;
  'scroll-morpher__content--gap-x-400': string;
  'scroll-morpher__content--gap-x-4000': string;
  'scroll-morpher__content--gap-x-500': string;
  'scroll-morpher__content--gap-x-600': string;
  'scroll-morpher__content--gap-x-700': string;
  'scroll-morpher__content--gap-x-800': string;
  'scroll-morpher__content--gap-y-0': string;
  'scroll-morpher__content--gap-y-100': string;
  'scroll-morpher__content--gap-y-1000': string;
  'scroll-morpher__content--gap-y-1200': string;
  'scroll-morpher__content--gap-y-1400': string;
  'scroll-morpher__content--gap-y-1600': string;
  'scroll-morpher__content--gap-y-200': string;
  'scroll-morpher__content--gap-y-2000': string;
  'scroll-morpher__content--gap-y-2400': string;
  'scroll-morpher__content--gap-y-300': string;
  'scroll-morpher__content--gap-y-400': string;
  'scroll-morpher__content--gap-y-4000': string;
  'scroll-morpher__content--gap-y-500': string;
  'scroll-morpher__content--gap-y-600': string;
  'scroll-morpher__content--gap-y-700': string;
  'scroll-morpher__content--gap-y-800': string;
  'scroll-morpher__item': string;
  'scroll-morpher__strip': string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
